### ISSUE TITLE
GitHub workflow caching doesn't take full Python version into account

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-python#560]
# Bug Report

Windows Python 3.12 tests have started failing due to a mismatch between the installed Python and the cached venv: https://github.com/ni/measurementlink-python/actions/runs/7215371883/job/19659513972

```
Run actions/setup-python@v5
  with:
    python-version: 3.[1](https://github.com/ni/measurementlink-python/actions/runs/7215371883/job/19659513972#step:3:1)[2](https://github.com/ni/measurementlink-python/actions/runs/7215371883/job/19659513972#step:3:2)
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
  env:
    POETRY_VERSION: 1.2.2
Installed versions
  Successfully set up CPython ([3](https://github.com/ni/measurementlink-python/actions/runs/7215371883/job/19659513972#step:3:3).12.1)
```

```
Run poetry install -v

  CalledProcessError

  Command 'D:\a\measurementlink-python\measurementlink-python\.venv\Scripts\python.exe -W ignore -' returned non-zero exit status 103.

  at C:\hostedtoolcache\windows\Python\3.[12](https://github.com/ni/measurementlink-python/actions/runs/7215371883/job/19659513972#step:6:13).1\x64\Lib\subprocess.py:571 in run
       567|             # We don't call process.wait() as .__exit__ does that for us.
       568|             raise
       569|         retcode = process.poll()
       570|         if check and retcode:
    >  571|             raise CalledProcessError(retcode, process.args,
       572|                                      output=stdout, stderr=stderr)
       573|     return CompletedProcess(process.args, retcode, stdout, stderr)
       574| 
       575| 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command D:\a\measurementlink-python\measurementlink-python\.venv\Scripts\python.exe -W ignore - errored with the following return code 103, and output: 
  No Python at '"C:\hostedtoolcache\windows\Python\3.12.0\x64\python.exe'

  input was : import sys
  
  if hasattr(sys, "real_prefix"):
      print(sys.real_prefix)
  elif hasattr(sys, "base_prefix"):
      print(sys.base_prefix)
  else:
      print(sys.prefix)
  

  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\utils\env.py:[14](https://github.com/ni/measurementlink-python/actions/runs/7215371883/job/19659513972#step:6:15)76 in _run
      1472|                 output = subprocess.check_output(
      1[47](https://github.com/ni/measurementlink-python/actions/runs/7215371883/job/19659513972#step:6:48)3|                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474|                 )
      1475|         except CalledProcessError as e:
    > 1476|             raise EnvCommandError(e, input=input_)
      1477| 
      1478|         return decode(output)
      1479| 
      1[48](https://github.com/ni/measurementlink-python/actions/runs/7215371883/job/19659513972#step:6:49)0|     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:
Error: Process completed with exit code 1.
```

## Repro or Code Sample

Create a PR.

## Expected Behavior

The tests pass.

## Current Behavior

`No Python at '"C:\hostedtoolcache\windows\Python\3.12.0\x64\python.exe'`

## Possible Solution

Use full Python version in the cache key.

## Context

Developing ni-measurementlink-service.

## Your Environment

GitHub

[AB#2605083](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2605083)
